main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('hobbies/', views.hobbies, name='hobbies'),
    path('experiences/', views.experiences, name='experiences'),
    path('contact/', views.contact, name='contact'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include
from story_8.views import fungsi_data

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story_5.urls')),
    path('story1/', include('story_1.urls')),
    path('story6/', include('story_6.urls')),
    path('story7/', include('story_7.urls')),
    path('story8/', include('story_8.urls')),
    path('data/', fungsi_data),
    path('story9/', include('story_9.urls')),
]

story_9/urls.py
from django.urls import path
from . import views

app_name = 'story_9'

urlpatterns = [
    path('',views.story9, name='story9'),
    path('signup/', views.signupPage, name='signup'),
	path('login/', views.loginPage, name='login'),  
	path('logout/', views.logoutPage, name='logout'),
]

story_9/models.py
from django.db import models

# Create your models here.

story_9/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

story_9/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import *
from .forms import CreateUserForm

def signupPage(request):
	if request.user.is_authenticated:
		return redirect('/story9/')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')

				return redirect('/story9/')
			

		context = {'form':form}
		return render(request, 'signup.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect('/story9/')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('/story9/')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'login.html', context)

def logoutPage(request):
	logout(request)
	return redirect('/story9/login')

@login_required(login_url='/story9/login')
def story9(request):
    return render(request, 'story9.html')

story_9/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
<style>
    #container-login{
        margin-top: 18%;
        padding-top: 30px;
        padding-bottom: 30px;
        background-color:#F3E2E2;
        max-width:  40rem;
        padding-left: 5%;
        padding-right: 5%;
    }
    #username{
        border-left: 0px; 
        border-right: 0px; 
        border-top: 0px; 
        background-color: transparent;
        display: block;
    }
    #password{
        border-left: 0px; 
        border-right: 0px; 
        border-top: 0px; 
        background-color: transparent;
        display: block;
    }
    input{
        width: 100%;
    }
</style>
{% endblock meta %}

{% block content %}
<div  class="container" style="margin-bottom: 10%;">
    <div class="container" id="container-login">
        <h1 style="text-align: center;">LOGIN</h1>
        <p style="text-align: center;">Please login first to continue</p>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label for="username" class="col-sm-2 col-form-label">Username</label>
                <div class="col-sm-10">
                  <input type="text" id="username" name= "username">
                </div>
              </div>
              <div class="form-group row">
                <label for="password" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                  <input type="password" id="password" name="password">
                </div>
              </div>
            <br>
            <input class="btn btn-dark login_btn" type="submit" value="Login">
        </form>
        <br>
        {% for message in messages %}
        <p id="messages">{{message}}</p>
        {% endfor %}	
        <p style="text-align: center;">
            Don't have any account? Please register first
            <a href="{%url 'story_9:signup'%}"><br>
                Register here</a>
        </p>
    </div>
<div>
{% endblock content %}

story_9/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
<style>
    #container-login{
        margin-top: 18%;
        padding-top: 30px;
        padding-bottom: 30px;
        background-color:#F3E2E2;
        max-width:  40rem;
        padding-left: 5%;
        padding-right: 5%;
    }
    #username{
        border-left: 0px; 
        border-right: 0px; 
        border-top: 0px; 
        background-color: transparent;
        display: block;
    }
    input{
        width: 100%;
        border-top: 0px;
        border-left: 0px;
        border-right: 0px;
        background-color: transparent;
    }

</style>
{% endblock meta %}

{% block content %}
<div  class="container" style="margin-bottom: 10%;">
    <div class="container" id="container-login">
        <h1 style="text-align: center;">SIGN UP</h1>
        <p style="text-align: center;">Please register if you don't have any account</p>
        <br>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label for="username" class="col-sm-2 col-form-label">Username</label>
                <div class="col-sm-10">
                    {{form.username}}
                </div>
              </div>
              <div class="form-group row">
                <label for="email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    {{form.email}}
                </div>
              </div>
              <div class="form-group row">
                <label for="email" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                    {{form.password1}}
                </div>
              </div>
              <div class="form-group row">
                <label for="email" class="col-sm-2 col-form-label">Confirm password</label>
                <div class="col-sm-10">
                    {{form.password2}}
                </div>
              </div>
            <br>
            <input class="btn btn-dark login_btn" type="submit" value="Sign Up" style="margin-left: 0px;">
        </form>
        <br>
        {{form.errors}}
        <br>
        <p style="text-align: center;">
            Already have account?
            <a href="{%url 'story_9:login'%}"><br>
                Login here</a>
        </p>
    </div>
<div>
{% endblock content %}

story_9/templates/story9.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
<style>
    img {
  border: 15px solid #F3E2E2;
    }
  #button-logout{
      margin-top: 10%;
      min-height: 20%;
  }
  @media screen and (max-width: 700px) {
    #button-logout {
        margin-top: 20%;
    }
  }
</style>
{% endblock meta %}

{% block content %}
<div  class="container" style="margin-bottom: 10%;">
    <div id="button-logout" style="text-align:right;">
        <a class="btn btn-dark"  href="{% url 'story_9:logout' %}" >Logout</a>
    </div>
    <h1 class="centertitle" style="margin-top: 20px;">Hello {{user.username}}!</h1>
    <br>
    <div style="text-align: center;">
        <img src="{% static 'welcoming.gif' %}" class="img-fluid" alt="Responsive image" >
        <br>
    </div>
<div>
{% endblock content %}