main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('hobbies/', views.hobbies, name='hobbies'),
    path('experiences/', views.experiences, name='experiences'),
    path('contact/', views.contact, name='contact'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include
from story_8.views import fungsi_data

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story_5.urls')),
    path('story1/', include('story_1.urls')),
    path('story6/', include('story_6.urls')),
    path('story7/', include('story_7.urls')),
    path('story8/', include('story_8.urls')),
    path('data/', fungsi_data),
    path('story9/', include('story_9.urls')),
]

story_6/urls.py
from django.urls import path
from . import views

app_name = 'story_6'

urlpatterns = [
    path('addparticipant/<int:activity_id>',views.addparticipant,name='addparticipant'),
    path('addactivity/',views.addactivity,name='addactivity'),
    path('',views.story6, name='story6'),
]

story_6/models.py
from django.db import models

# Create your models here.

class Activities(models.Model):
    Activity = models.CharField(max_length=30)
    Description = models.TextField(max_length=70)


def __str__(self):
    return self.Activity

class Participants(models.Model):
    Name = models.CharField(max_length=30)
    activity = models.ForeignKey(Activities, on_delete=models.CASCADE)

    def __str__(self):
        return self.Name

story_6/forms.py
from django import forms

from .models import Activities
from .models import Participants

class ActivitiesForm(forms.ModelForm):
    class Meta:
        model = Activities
        fields = [
            'Activity',
            'Description',
        ]

        widgets = {
            'Activity': forms.TextInput(attrs={'class': 'form-control',}),
            'Description': forms.Textarea(attrs={'class': 'form-control',}),
        }

class ParticipantsForm(forms.ModelForm):
    class Meta:
        model = Participants
        fields = [
            'Name',
        ]

        widgets = {
            'Name': forms.TextInput(attrs={'class': 'form-control',}),
        }

story_6/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.

from .forms import ActivitiesForm
from .forms import ParticipantsForm
from .models import Activities
from .models import Participants



def addparticipant(request,activity_id):
    participants = Participants.objects.all()
    activity = Activities.objects.get(id=activity_id)
    participants_form = ParticipantsForm(request.POST or None)

    if request.method == 'POST':
        if participants_form.is_valid():
            participants.create(
                Name = participants_form.data['Name'],
                activity = activity
            )
            return HttpResponseRedirect("/story6/")  

    context = {
        'page_title':'ADD PARTICIPANT',
        'participants_form': participants_form,
    }

    return render(request,'addparticipant.html',context)



def story6(request):
    participants = Participants.objects.all()
    activities = Activities.objects.all()
    context = {
        'page_title':'ACTIVITIES',
        'activities':activities,
        'participants':participants,
    }
    return render(request,'story6.html',context)


def addactivity(request):
    activities_form = ActivitiesForm(request.POST or None)

    if request.method == 'POST':
        if activities_form.is_valid():
            activities_form.save()

            return HttpResponseRedirect("/story6/")  

    context = {
        'page_title':'ADD ACTIVITY',
        'activities_form':activities_form,
    }

    return render(request,'addactivity.html',context)

story_6/templates/addactivity.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Add Activity</title>
{% endblock meta %}

{% block content %}
<h1 class="centertitle">{{page_title}}</h1>

<div class="container" style="max-width: 40rem;">
<form method= "POST">
  {%csrf_token%}
  {%for form in activities_form%}
  <div class="form-group">
    {{form.label}}
    {{form}}
    </div>
  {% endfor %}

<button type="submit" class="btn btn-dark" style="margin-bottom: 25px;">Send</button>
</form>
</div>
{% endblock content %}

story_6/templates/addparticipant.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Add Participant</title>
{% endblock meta %}

{% block content %}
<h1 class="centertitle">{{page_title}}</h1>

<div class="container" style="max-width: 40rem;">
<form method= "POST">
  {%csrf_token%}
  {%for form in participants_form%}
  <div class="form-group">
    {{form.label}}
    {{form}}
    </div>
  {% endfor %}

<button type="submit" class="btn btn-dark" style="margin-bottom: 25px;">Send</button>
</form>
</div>
{% endblock content %}

story_6/templates/story6.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story6</title>
{% endblock meta %}

{% block content %}

<div class="container">
  <h1 class="centertitle">{{page_title}}</h1>
  <a class="btn btn-lg btn-dark" href="/story6/addactivity" style="margin-bottom: 30px;">Add more</a>
  <div class="row">
    {% for activity in activities %}
    <div class="col-md-4">
      <div class="card" style="margin-bottom: 20px; background-color: #F3E2E2;">
        <div class="card-body">
          <h5 class="card-title"><b>Activity: {{activity.Activity}}</b></h5>
          <p><b>Description:</b> {{activity.Description}}</p>
          <p>Participants:</p>
          {%for participant in participants %}
                {%if participant.activity == activity%}
                <p>{{participant.Name}}</p>
                {% endif %}
            {%endfor%}
          <a class="btn btn-dark" href="{% url 'story_6:addparticipant' activity_id=activity.id%}" style="width: min-content; margin-right: 30px;">Add Participant</a>
        </div>
      </div>
    </div>
    {%endfor%}
  </div>
</div>
{% endblock content %}