main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('hobbies/', views.hobbies, name='hobbies'),
    path('experiences/', views.experiences, name='experiences'),
    path('contact/', views.contact, name='contact'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include
from story_8.views import fungsi_data

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story_5.urls')),
    path('story1/', include('story_1.urls')),
    path('story6/', include('story_6.urls')),
    path('story7/', include('story_7.urls')),
    path('story8/', include('story_8.urls')),
    path('data/', fungsi_data),
    path('story9/', include('story_9.urls')),
]

story_5/urls.py
from django.urls import path
from . import views
from .views import PostDetailView

app_name = 'story_5'

urlpatterns = [
    path('detail/<pk>/',PostDetailView.as_view(),name='detail'),
    path('delete/(?P<delete_id>[0-9]+)',views.delete,name='delete'),
    path('create/',views.create,name='create'),
    path('',views.story5, name='story5'),
]

story_5/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    Course = models.CharField(max_length=30)
    Lecturer = models.CharField(max_length=30)
    Credits = models.PositiveIntegerField()
    Description = models.TextField(max_length=150)
    Term = models.CharField(max_length =20)
    Room = models.CharField(max_length =20)

    # published = models.DateTimeField(auto_now_add = True)
    # updated = models.DateTimeField(auto_now =True)

def __str__(self):
    return "{}. {}".format(self.id, self.Course)

story_5/forms.py
from django import forms

# class PostForm(forms.Form):
#     nama = forms.CharField(max_length=20)
#     dosen = forms.CharField(max_length=20)
#     sks = forms.CharField(max_length=20)
#     deskripsi = forms.CharField(
#         widget = forms.Textarea
#         )
#     semester= forms.CharField(max_length=20)
#     ruangan= forms.CharField(max_length=20)

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'Course',
            'Lecturer',
            'Credits',
            'Description',
            'Term',
            'Room',
        ]

        widgets = {
            'Course': forms.TextInput(attrs={'class': 'form-control',}),
            'Lecturer': forms.TextInput(attrs={'class': 'form-control',}),
            'Credits': forms.NumberInput(attrs={'class': 'form-control',}),
            'Description': forms.Textarea(attrs={'class': 'form-control',}),
            'Term': forms.TextInput(attrs={'class': 'form-control',}),
            'Room': forms.TextInput(attrs={'class': 'form-control',}),
        }

story_5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.

from .forms import PostForm
from .models import Post
from django.views.generic.detail import DetailView

class PostDetailView(DetailView):
    model = Post
    template_name = "detail.html"

def delete(request,delete_id):
    Post.objects.filter(id=delete_id).delete()
    return HttpResponseRedirect("/story5/")

# def detail(request,detail_id):
#     return render(request,"/detail/%s/"%(detail_id))

def story5(request):
    posts = Post.objects.all()
    context = {
        'page_title':'COURSES',
        'posts':posts,
    }
    return render(request,'story5.html',context)

def create(request):
    post_form = PostForm(request.POST or None)

    if request.method == 'POST':
        if post_form.is_valid():
            post_form.save()

            return HttpResponseRedirect("/story5/")  

    context = {
        'page_title':'ADD COURSE',
        'post_form':post_form,
    }

    return render(request,'create.html',context)

story_5/templates/create.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story5</title>
{% endblock meta %}

{% block content %}
<h1 class="centertitle">{{page_title}}</h1>

<div class="container" style="max-width: 40rem;">
<form method= "POST">
  {%csrf_token%}
  {%for form in post_form%}
  <div class="form-group">
    {{form.label}}
    {{form}}
    </div>
  {% endfor %}

<button type="submit" class="btn btn-dark" style="margin-bottom: 25px;">Send</button>
</form>
</div>
{% endblock content %}

story_5/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story5</title>
{% endblock meta %}

{% block content %}
<h1 class="centertitle">{{post.Course}}</h1>

<div class="container" style="max-width: 40rem;">
    <div class="container-detail">
    <p><b>Lecturer:</b> {{post.Lecturer}}</p>
    <p><b>Credits:</b> {{post.Credits}}</p>
    <p><b>Description:</b> {{post.Description}}</p>
    <p><b>Term:</b> {{post.Term}}</p>
    <p><b>Room:</b> {{post.Room}}</p>
    </div>
    <a class="btn btn-lg btn-dark" href="/story5" style="margin-bottom: 30px; margin-left: 10px;">Back to courses</a>
</div>
{% endblock content %}

story_5/templates/story5.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story5</title>
{% endblock meta %}

{% block content %}

<div class="container">
  <h1 class="centertitle">{{page_title}}</h1>
  <a class="btn btn-lg btn-dark" href="/story5/create" style="margin-bottom: 30px;">Add more</a>
  <div class="row">
    {% for post in posts %}
    <div class="col-md-4">
      <div class="card" style="margin-bottom: 20px; background-color: #F3E2E2;">
        <div class="card-body">
          <h5 class="card-title"><b>Course: {{post.Course}}</b></h5>
          <p><b>Credits:</b> {{post.Credits}}</p>
          <a class="btn btn-dark" href="{% url 'story_5:detail' post.id %}" style="width: min-content; margin-right: 30px;">Detail</a>
          <a class="btn btn-danger" href="{% url 'story_5:delete' post.id %}" style="width: min-content; margin-right: auto;">Delete</a>
        </div>
      </div>
    </div>
    {%endfor%}
  </div>
</div>
{% endblock content %}